name: Generate snake animation

on:
  push:
    branches:
      - main  # Ana dalda tetiklenmesi için
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: hamz011  # GitHub kullanıcı adınızı yazın
          outputs: dist/snake.svg?palette=github-dark  # Renk paleti ve dosya yolu

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist  # Yılan animasyonunun bulunduğu dizin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
